name: Remove Dev
on:
  workflow_dispatch:
    inputs:
      model_name:
        required: true
        description: Model supported by sentence-transformers such as intfloat/e5-large-v2, sentence-transformers/all-MiniLM-L6-v2, sentence-transformers/all-mpnet-base-v2

jobs:
  rm-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
      - name: Remove Lambda functions
        run: >
          SERVICE=$(echo "${{ github.event.inputs.model_name }}" | cut -d'/' -f2)
          MODEL=${{ github.event.inputs.model_name }}
          MEMORY_SIZE=
          NORMALIZE_EMBEDDINGS=
          sls remove
